### ISSUE TITLE
Bower package

### ISSUE THREAD

**Issue by bakurin** [Ingenico-ePayments/connect-sdk-client-js#1]
It would be nice to use [Bower](https://bower.io/) to install the library. Is it possible to publish the library as Bower package?

**Comment by lucienimmink** [comment]
It's on bower; globalcollect-sdk-client-js; the bower package links to this github btw

**Comment by bakurin** [comment]
My bad. But any way there is no a distribute folder in the package.  I'd like to avoid to build the lib by myself. Is it possible to add `dist/` folder to the package?

**Comment by lucienimmink** [comment]
This is now done in version 2.1.0 of the SDK.
