### ISSUE TITLE
3D Secure in react-native applications

### ISSUE THREAD

**Issue by mbd-fondative** [Ingenico-ePayments/connect-sdk-client-js#10]
Hi,
How to integrate the 3D Secure service in react-native application ??
How to replace the returnUrl ??

**Comment by LeonStemerdink** [comment]
Hello,
The Ingenico Connect Client SDKs do not contain any functionality that is specific to 3DS Secure.
You can find more information about working with 3D Secure on the Ingenico Connect platform [here](https://epayments.developer-ingenico.com/best-practices/services/).

**Comment by mbd-fondative** [comment]
Hi,
In the parameters of request 3DS , we have the attribute returnUrl !! how to use this in mobile applications?? 

>   "order" : {
          "amountOfMoney" : {
              "currencyCode" : "EUR",
              "amount" : 2980
          },
          "customer" : {
              "billingAddress" : {
                  "countryCode" : "NL"
              }
          }
      },
      "cardPaymentMethodSpecificInput" : {
          "paymentProductId" : 1,
          "returnUrl" : "https://www.example.com",
          "card" : {
              "cvv" : "123",
              "cardNumber" : "4567350000427977",
              "expiryDate" : "1220",
              "cardholderName" : "Wile E. Coyote"
          }
      }
}
