### ISSUE TITLE
npm distribution does not provide forge dependency

### ISSUE THREAD

**Issue by Bartvaderkin** [Ingenico-ePayments/connect-sdk-client-js#17]
I installed the SDK from npm but when I try to run the encrypted version it raises about undefined 'forge'. When I look into it this seems to be a third part encryption library? As a dependency I'd expect it to be installed with the package.

I see it minified in the examples repos but it is very old and the webpack example readme notes we have to update it: 

https://github.com/Ingenico-ePayments/connect-sdk-client-js-example/tree/master/minimal-webpack

**Comment by rob-spoor** [comment]
In version 4.0.0 it was added as a non-development dependency. For some module loaders and module bundlers you may need to make changes. For instance, requirejs needs a `node-forge` module. The example apps have been updated together with the SDK to show how to use the updated SDK.
