### ISSUE TITLE
dataRestrictions - field cardholderName is required now

### ISSUE THREAD

**Issue by Jonitu** [Ingenico-ePayments/connect-sdk-client-js#20]
Since yesterday, 10/Aug, the Get Payment Product api is returning the cardholderName field as mandatory. This is causing a problem in our application. In STAG this field is not mandatory, only in Production. Is it possible to remove this mandatory field?
API: https://ams1.api-ingenico.com/client/v1/.../products/1?countryCode=AR&isRecurring=false&amount=180000&currencyCode=ARS&locale=es_ES&cacheBust=1628706586336

`{
      "dataRestrictions" : {
         "isRequired" : true,
         "validators" : {
            "length" : {
               "maxLength" : 50,
               "minLength" : 2
            },
            "regularExpression" : {
               "regularExpression" : "^[-\\sA-Za-z0-9ªºÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝßàáâãäåæçèéêëìíîïðñòóôõöøùúûüýÿĀāĂăĄąĆćĈĉĊċČčĎďĐđĒēĔĕĖėĘęĚěĜĝĞğĠġĢģĤĥĦħĨĩĪīĬĭĮįİıĲĳĴĵĶķĹĺĻļĽľĿŀŁłŃńŅņŇňŉŌōŎŏŐőŒœŔŕŖŗŘřŚśŜŝŞşŠšŢţŤťŦŧŨũŪūŬŭŮůŰűŲųŴŵŶŷŸŹźŻżŽžſƒƠơƯưǍǎǏǐǑǒǓǔǕǖǗǘǙǚǛǜǺǻǼǽǾǿȘșȚțΆΈΉΊΌΎΏΑΓΔΕΖΗΙΚΛΝΟΡΣΥΩΪΫάέήίαβγδεζηικλμνξοπρςστυψωϊϋόύώЁЄЇАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёєїҐґẠạẢảấẦầẨẩẪẫẬậẮắẰằẲẳẴẵẶặẸẹẺẻẼẽẾếỀềỂểỄễỆệỈỉỊịỌọỎỏỐốỒồỔổỖỗỘộỚớỜờỞởỠỡỢợỤụỦủỨứỪừỬửỮữỰựỲỳỴỵỶỷỸỹ.'/]+$"
            }
         }
      },
      "displayHints" : {
         "alwaysShow" : false,
         "displayOrder" : 1142,
         "formElement" : {
            "type" : "text"
         },
         "label" : "Nombre del titular de la tarjeta",
         "obfuscate" : false,
         "placeholderLabel" : "John Doe",
         "preferredInputType" : "StringKeyboard"
      },
      "id" : "cardholderName",
      "type" : "string"
   }`

**Comment by romanflopez** [comment]
any news ? same problem here

**Comment by LeonStemerdink-Worldline** [comment]
Hello Jonitu,

The requirements of 3-D Secure Version 2.x state that in most cases it is mandatory to provide the name of the cardholder. Due to this requirement, the property carholderName is returned as being mandatory for a card payment request. It can not be removed. If you face issues with this property being required for your implementation, please align with your merchant implementation manager for a temporary solution.
