### ISSUE TITLE
AndroidPay is not defined

### ISSUE THREAD

**Issue by SkinyMonkey** [Ingenico-ePayments/connect-sdk-client-js#3]
When I used the webpack example i got this error in src/AndroidPay.js

I'll fix this in a PR

**Comment by Ronaldvdh-ISAAC** [comment]
Hi SkinyMonkey,
The development team has this issue under investigation and will comeback to you shortly

**Comment by SkinyMonkey** [comment]
Hi, the PR shows exactly what's wrong and how to solve it.

**Comment by Ronaldvdh-ISAAC** [comment]
Hi SkinyMonkey,
Your PR did solve the webpack error, but this was not the right fix for it.
A new release will be made available shortly, which will fix your issue.

**Comment by rikvanthof** [comment]
Fixed with the new updated version that was pushed today.
