### ISSUE TITLE
Authorization header 'clientSessionId' is empty

### ISSUE THREAD

**Issue by SkinyMonkey** [Ingenico-ePayments/connect-sdk-client-js#5]
``` 
import connect from 'connect-sdk-client-js/dist/connectsdk.js';
[...]     {
               //sessionDetails is coming from our APi:  
               //sessionDetails = {clientSessionId: "...",
               //                              customerId: "...",
               //                              region: "EU",
               //                              environment: "PREPROD"}
               const session = new connect(sessionDetails);

                const ingenicoPaymentDetails = {
                  totalAmount: paymentDetails.amount,
                  countryCode: currentUser.country,
                  locale: `${currentUser.locale}_${currentUser.country}`,
                  currency: paymentDetails.currencyCode.toUpperCase(),
                  isRecurring: false
                };

                return createPayload(session, cardDetails, ingenicoPaymentDetails);
}
```

Using this code, when i use the createPayload given in the requirejs example to test :

```https://github.com/Ingenico-ePayments/connect-sdk-client-js-example/blob/master/minimal-requirejs/js/create-payload.js```

I can observe that the Authorization header of the request sent by `getIINdetails` has this value:

```Authorization: GCS v1Client:undefined```

I checked and rechecked : the clientSessionId is set properly in sessionDetails.

The code is mostly based on what i found in the webpack example by the way.

Could you please help me with this?

**Comment by rob-spoor** [comment]
I've checked both the code and the documentation and the implementation, and there is an inconsistency. The documentation mentions `clientSessionId`, but the implementation uses `clientSessionID`. The latter is correctly documented on https://epayments.developer-ingenico.com/documentation/sdk/mobile/javascript/ but incorrectly documented on the API references. The latter will need to be updated.

**Comment by SkinyMonkey** [comment]
Thanks man ... I would have never noticed this 1 char difference ...

**Comment by SkinyMonkey** [comment]
Other inconsistency I just found : 

The expirydate field is called in camelCase (expiryDate) in the examples, I found not trace of a expiryDate in the actual sdk code.

**Comment by vibdheeraj** [comment]
@rikvanthof Can we use connect-sdk-client-js in React-native ?

**Comment by rob-spoor** [comment]
As I said in https://github.com/Ingenico-ePayments/connect-sdk-client-js/issues/9, this is not possible at the moment.
